#!/usr/bin/env bash
# Idempotent repository bootstrap: install dependencies, create local backend
# config, and seed the MongoDB database with demo data.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# shellcheck source=/dev/null
source "$SCRIPT_DIR/mongo.sh"

# --legacy-peer-deps mirrors the root .npmrc; it is passed explicitly because
# npm only reads the project-level .npmrc from the current directory, and the
# frontend has peer-dependency conflicts (vitest 3 vs @vitest/coverage-v8 4).
echo "== Installing npm dependencies (root, backend, frontend, admin, driver) =="
npm install --legacy-peer-deps
( cd backend && npm install --legacy-peer-deps )
( cd frontend && npm install --legacy-peer-deps )
( cd admin && npm install --legacy-peer-deps )
( cd driver && npm install --legacy-peer-deps )

echo "== Ensuring backend/.env exists (local development defaults) =="
if [ ! -f backend/.env ]; then
  cat > backend/.env <<'EOF'
# Local development configuration (generated by .cursor/install.sh).
# These are non-secret defaults suitable for a local dev database only.
NODE_ENV=development
PORT=5000
HOST=0.0.0.0
MONGODB_URI=mongodb://127.0.0.1:27017/pet-ecommerce
JWT_SECRET=dev-local-jwt-secret-change-me-minimum-32-characters
JWT_REFRESH_SECRET=dev-local-jwt-refresh-secret-change-me-32-chars
FRONTEND_URL=http://localhost:5173
ADMIN_URL=http://localhost:5174
CORS_ORIGIN=http://localhost:5173,http://localhost:5174,http://localhost:5175
AUTO_CREATE_ADMIN=true
ADMIN_EMAIL=admin@petshiwu.com
ADMIN_PASSWORD=admin123
EOF
  echo "Created backend/.env"
else
  echo "backend/.env already exists; leaving it untouched."
fi

# The admin dashboard (and some frontend widgets) default their API base URL to
# the production host when VITE_API_URL is unset. Point them at the local Vite
# proxy so the apps talk to the local backend during development.
echo "== Ensuring frontend/.env and admin/.env point at the local backend =="
if [ ! -f frontend/.env ]; then
  echo "VITE_API_URL=/api" > frontend/.env
  echo "Created frontend/.env"
else
  echo "frontend/.env already exists; leaving it untouched."
fi
if [ ! -f admin/.env ]; then
  echo "VITE_API_URL=/api" > admin/.env
  echo "Created admin/.env"
else
  echo "admin/.env already exists; leaving it untouched."
fi

echo "== Seeding MongoDB with demo data =="
mongo_start "$MONGO_LOG_DIR/mongod-install.log"
( cd backend && npx ts-node src/scripts/seed.ts )
mongo_stop

echo ""
echo "== Install complete =="
echo "Demo accounts: admin@petshiwu.com / admin123  |  customer@example.com / password123"
