import SEO from '@/components/SEO';

const PrivacyPolicy = () => {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <SEO
        title="Privacy Policy | PetShiwu"
        description="PetShiwu's Privacy Policy explains how we collect, use, and protect your personal information when you shop with us."
        url="/privacy"
      />

      <h1 className="text-4xl font-black mb-2 text-gray-900">Privacy Policy</h1>
      <p className="text-gray-500 mb-8">Last updated: May 20, 2026</p>

      <div className="prose prose-gray max-w-none space-y-8 text-gray-700 leading-relaxed">

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-3">1. Who We Are</h2>
          <p>
            PetShiwu ("we," "our," or "us") is an online pet supply store located at 37-68 74th St,
            Jackson Heights, NY 11372. We operate the website <strong>petshiwu.com</strong> and are
            committed to protecting the privacy of every customer and visitor.
          </p>
          <p className="mt-2">
            Questions about this policy? Contact us at{' '}
            <a href="mailto:support@petshiwu.com" className="text-blue-600 hover:underline">
              support@petshiwu.com
            </a>{' '}
            or call <a href="tel:+18002592605" className="text-blue-600 hover:underline">+1 (800) 259-2605</a>.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-3">2. Information We Collect</h2>
          <p>We collect information you give us directly, and information generated by your use of our site:</p>
          <ul className="list-disc pl-6 mt-3 space-y-2">
            <li><strong>Account information:</strong> Name, email address, and password when you create an account.</li>
            <li><strong>Order information:</strong> Shipping address, billing address, and order history when you place an order.</li>
            <li><strong>Payment information:</strong> Payment is processed by our secure payment partners (Stripe, PayPal). We do not store full card numbers on our servers.</li>
            <li><strong>Communications:</strong> Messages you send us via email or our contact form.</li>
            <li><strong>Usage data:</strong> Pages visited, search queries, and browsing behavior to improve our site.</li>
            <li><strong>Device information:</strong> IP address, browser type, and operating system for security and analytics.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-3">3. How We Use Your Information</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>Process and fulfill your orders, including shipping and returns.</li>
            <li>Send order confirmations, shipping updates, and account notifications.</li>
            <li>Respond to customer service requests and questions.</li>
            <li>Improve and personalize your shopping experience.</li>
            <li>Send promotional emails (only with your consent — you can unsubscribe at any time).</li>
            <li>Prevent fraud and maintain the security of our site.</li>
            <li>Comply with applicable laws and regulations.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-3">4. Cookies and Tracking</h2>
          <p>
            We use cookies and similar technologies to improve your experience, remember your preferences,
            analyze traffic, and support our marketing. You can control cookies through your browser settings.
            Disabling cookies may affect some site features.
          </p>
          <p className="mt-2">We use the following types of cookies:</p>
          <ul className="list-disc pl-6 mt-3 space-y-2">
            <li><strong>Essential cookies:</strong> Required for the site to function (e.g., your shopping cart).</li>
            <li><strong>Analytics cookies:</strong> Help us understand how visitors use the site.</li>
            <li><strong>Marketing cookies:</strong> Used to show you relevant ads on other platforms.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-3">5. How We Share Your Information</h2>
          <p>We do not sell your personal information. We share your data only with:</p>
          <ul className="list-disc pl-6 mt-3 space-y-2">
            <li><strong>Payment processors</strong> (Stripe, PayPal) to complete transactions.</li>
            <li><strong>Shipping carriers</strong> to deliver your orders.</li>
            <li><strong>Email service providers</strong> to send transactional and marketing emails.</li>
            <li><strong>Analytics platforms</strong> (e.g., Google Analytics) to improve our services.</li>
            <li><strong>Law enforcement or government</strong> when required by law.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-3">6. Your Rights</h2>
          <p>Depending on where you live, you may have the following rights:</p>
          <ul className="list-disc pl-6 mt-3 space-y-2">
            <li><strong>California residents (CCPA):</strong> Right to know what data we collect, right to delete your data, and right to opt out of data sales (we do not sell data).</li>
            <li><strong>EU/UK residents (GDPR):</strong> Right to access, correct, delete, restrict, or port your data. Right to object to processing. Right to withdraw consent.</li>
            <li><strong>All customers:</strong> You can update your account information at any time by logging in or contacting us.</li>
          </ul>
          <p className="mt-2">
            To exercise any of these rights, email us at{' '}
            <a href="mailto:support@petshiwu.com" className="text-blue-600 hover:underline">support@petshiwu.com</a>.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-3">7. Data Security</h2>
          <p>
            We use industry-standard security measures including 256-bit SSL encryption, secure data storage,
            and access controls to protect your personal information. However, no online system is 100% secure,
            and we cannot guarantee absolute security.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-3">8. Data Retention</h2>
          <p>
            We retain your personal information for as long as your account is active or as needed to provide
            services, comply with legal obligations, resolve disputes, and enforce our agreements.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-3">9. Children's Privacy</h2>
          <p>
            Our site is not directed to children under 13 years of age. We do not knowingly collect personal
            information from children. If you believe a child has provided us with their data, please contact us
            and we will delete it promptly.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-3">10. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. We will notify you of significant changes by
            posting the new policy on this page with an updated date. Your continued use of the site after
            changes constitutes acceptance of the revised policy.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-3">11. Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, please contact us:</p>
          <div className="mt-3 bg-gray-50 rounded-xl p-5 space-y-1">
            <p><strong>PetShiwu</strong></p>
            <p>37-68 74th St, Jackson Heights, NY 11372</p>
            <p>Email: <a href="mailto:support@petshiwu.com" className="text-blue-600 hover:underline">support@petshiwu.com</a></p>
            <p>Phone: <a href="tel:+18002592605" className="text-blue-600 hover:underline">+1 (800) 259-2605</a></p>
          </div>
        </section>

      </div>
    </div>
  );
};

export default PrivacyPolicy;
