#!/usr/bin/env python3
"""Compile seo_blog_topics.py into TypeScript catalogs for backend and frontend."""
from __future__ import annotations

import json
from pathlib import Path

from seo_blog_topics import TOPICS

ROOT = Path(__file__).resolve().parents[1]
BACKEND_OUT = ROOT / "backend/src/seo/trendingLearningPosts.ts"
FRONTEND_OUT = ROOT / "frontend/src/data/trendingLearningPosts.ts"
FRONTEND_META_OUT = ROOT / "frontend/src/data/trendingLearningMeta.ts"

VET_NOTE = (
    "This article is educational and is not a diagnosis or treatment plan. "
    "Ask your veterinarian before you change food, supplements, or medicine, "
    "and seek care right away for blood in stool or vomit, repeated vomiting, "
    "trouble breathing, collapse, or a pet that cannot keep water down."
)


def esc(text: str) -> str:
    return (
        str(text or "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def esc_keep_links(text: str) -> str:
    """Allow simple internal <a href> tags already present in topic copy."""
    return text


def render_html(topic: dict, titles: dict[str, str]) -> str:
    img = topic["img"]
    alt = esc(topic["alt"])
    parts: list[str] = [
        f"<p>{esc_keep_links(topic['intro'])}</p>",
        "<figure>",
        f'  <picture><source srcset="/blog/{img}.webp" type="image/webp" />',
        f'  <img src="/blog/{img}.jpg" alt="{alt}" width="1200" height="675" loading="eager" /></picture>',
        f"  <figcaption>{alt}</figcaption>",
        "</figure>",
    ]
    for index, section in enumerate(topic["sections"]):
        parts.append(f"<h2>{esc_keep_links(section['h'])}</h2>")
        for paragraph in section.get("p") or []:
            parts.append(f"<p>{esc_keep_links(paragraph)}</p>")
        bullets = section.get("ul") or []
        if bullets:
            parts.append("<ul>")
            parts.extend(f"<li>{esc_keep_links(item)}</li>" for item in bullets)
            parts.append("</ul>")
        if index == 2:
            parts.append(
                f'<p><img src="/blog/{img}.webp" alt="{alt}" width="1200" height="675" loading="lazy" /></p>'
            )
    parts.append("<h2>Shop this at Petshiwü</h2>")
    parts.append(f"<p>{esc_keep_links(topic['shop'])}</p>")
    parts.append(
        f'<p><a href="{esc(topic["shopPath"])}">Browse matching products at Petshiwü</a> — '
        "free shipping over $49, no autoship.</p>"
    )
    parts.append("<h2>Frequently asked questions</h2>")
    for faq in topic["faqs"]:
        parts.append(f"<h3>{esc_keep_links(faq['q'])}</h3>")
        parts.append(f"<p>{esc_keep_links(faq['a'])}</p>")
    parts.append("<h2>Related Petshiwü guides</h2>")
    parts.append("<ul>")
    for slug in topic["related"]:
        title = titles.get(slug, slug.replace("-", " ").title())
        parts.append(f'<li><a href="/learning/{esc(slug)}">{esc(title)}</a></li>')
    parts.append("</ul>")
    parts.append(f"<p><em>{VET_NOTE}</em></p>")
    return "\n".join(parts)


def to_post(topic: dict, titles: dict[str, str]) -> dict:
    published = topic["publishedAt"]
    if not published.endswith("Z") and "T" not in published:
        published = f"{published}T00:00:00.000Z"
    return {
        "slug": topic["slug"],
        "title": topic["title"],
        "description": topic["description"],
        "publishedAt": published,
        "html": render_html(topic, titles),
        "featuredImage": f"/blog/{topic['img']}.jpg",
        "featuredImageWebp": f"/blog/{topic['img']}.webp",
        "imageAlt": topic["alt"],
        "petType": topic["petType"],
        "category": topic["category"],
        "tags": topic["tags"],
        "excerpt": topic["description"],
        "shopPath": topic["shopPath"],
    }


def ts_meta_module(posts: list[dict]) -> str:
    meta = [{key: value for key, value in post.items() if key != "html"} for post in posts]
    payload = json.dumps(meta, ensure_ascii=False, indent=2)
    return f"""/* Generated by scripts/build_seo_blogs.py — listing metadata only. */
export type TrendingLearningMeta = {{
  slug: string;
  title: string;
  description: string;
  publishedAt: string;
  featuredImage: string;
  featuredImageWebp: string;
  imageAlt: string;
  petType: string;
  category: string;
  tags: string[];
  excerpt: string;
  shopPath: string;
}};

export const TRENDING_LEARNING_META: TrendingLearningMeta[] = {payload};
"""


def ts_module(posts: list[dict]) -> str:
    payload = json.dumps(posts, ensure_ascii=False, indent=2)
    return f"""/* Generated by scripts/build_seo_blogs.py — do not edit by hand. */
export type TrendingLearningPost = {{
  slug: string;
  title: string;
  description: string;
  publishedAt: string;
  html: string;
  featuredImage: string;
  featuredImageWebp: string;
  imageAlt: string;
  petType: string;
  category: string;
  tags: string[];
  excerpt: string;
  shopPath: string;
}};

export const TRENDING_LEARNING_POSTS: TrendingLearningPost[] = {payload};

export const TRENDING_LEARNING_BY_SLUG: Record<string, TrendingLearningPost> =
  Object.fromEntries(TRENDING_LEARNING_POSTS.map((post) => [post.slug, post]));
"""


def main() -> None:
    slugs = [topic["slug"] for topic in TOPICS]
    if len(slugs) < 106:
        raise SystemExit(f"Need at least 106 topics, got {len(slugs)}")
    if len(set(slugs)) != len(slugs):
        raise SystemExit("Duplicate slugs in TOPICS")
    titles = {topic["slug"]: topic["title"] for topic in TOPICS}
    posts = [to_post(topic, titles) for topic in TOPICS]
    source = ts_module(posts)
    BACKEND_OUT.write_text(source)
    FRONTEND_OUT.write_text(source)
    FRONTEND_META_OUT.write_text(ts_meta_module(posts))
    print(f"wrote {len(posts)} posts")
    print(BACKEND_OUT)
    print(FRONTEND_OUT)
    print(FRONTEND_META_OUT)


if __name__ == "__main__":
    main()
