/**
 * publishHowToGuides.mjs — 15 high-intent how-to guides
 * Targets the most-searched pet care queries in NYC
 */
const API_BASE = 'https://petshiwu.onrender.com';
async function login() {
  const res = await fetch(`${API_BASE}/api/auth/login`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({email:'admin@petshiwu.com',password:'@Admin,1+23as'}) });
  return (await res.json()).token;
}
async function pub(token, post) {
  const res = await fetch(`${API_BASE}/api/v1/blogs/admin`, { method:'POST', headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`}, body:JSON.stringify({...post,isPublished:true,publishedAt:new Date().toISOString()}) });
  const d = await res.json();
  const ok = d.success||d._id||d.data?._id;
  process.stdout.write(`${ok?'✅':'❌'} ${post.title.substring(0,72)}\n`);
  return ok;
}

const posts = [
  {
    title:'How to Clean Your Dog Ears at Home — Step-by-Step Guide',
    slug:'how-to-clean-dog-ears-at-home',
    petType:'dog', category:'Dog Care',
    tags:['how to clean dog ears','dog ear cleaning NYC','dog ear infection prevention','clean dog ears Queens'],
    img:'photo-1537151608828-ea2b11777ee8',
    meta:'How to clean your dog ears safely at home. Step-by-step guide, what products to use, and warning signs of infection. For NYC apartment dogs.',
    excerpt:'Dirty ears lead to infections — one of the most common and expensive vet visits. Here\'s how to clean your dog\'s ears safely at home in under 5 minutes.',
    content:`<h2>Why Ear Cleaning Matters</h2><p>Ear infections (otitis externa) are among the top 5 reasons dogs visit the vet. They're painful, expensive to treat, and almost always preventable with regular cleaning. Dogs with floppy ears (Cocker Spaniels, Basset Hounds, Beagles), heavy ear hair (Poodles, Bichons), or who swim often are especially prone.</p><h2>What You Need</h2><ul><li>Veterinary-formulated ear cleaner (not water, not hydrogen peroxide)</li><li>Cotton balls or gauze squares</li><li>Treats for positive reinforcement</li></ul><h2>Step-by-Step</h2><ol><li><strong>Position your dog:</strong> Have them sit or lie with the ear you're cleaning facing up. Have treats ready.</li><li><strong>Fill the canal:</strong> Squeeze the ear cleaner generously into the ear canal until it's visibly full. Don't insert the tip deeply.</li><li><strong>Massage the base:</strong> Hold the ear flap up and massage the base of the ear for 30 seconds. You'll hear a squishing sound — that's the cleaner breaking up debris.</li><li><strong>Let them shake:</strong> Step back and let your dog shake. This brings debris up from the canal.</li><li><strong>Wipe the visible area:</strong> Use cotton balls to wipe the visible parts of the ear. Never insert cotton swabs into the ear canal.</li><li><strong>Reward immediately.</strong></li></ol><h2>How Often</h2><ul><li>Floppy-eared dogs: every 2-4 weeks</li><li>Upright-eared dogs: every 4-6 weeks or as needed</li><li>After swimming: always</li></ul><h2>When to See a Vet</h2><p>If you see: redness, swelling, dark discharge (brown or black), yellow discharge, bad odor, or your dog is scratching intensely and shaking their head — stop cleaning and see a vet. These are signs of an active infection that needs treatment before cleaning.</p><p>Shop ear cleaning supplies at <a href="https://www.petshiwu.com/dog">PetShiwu</a> — delivered to Queens, Brooklyn, and all of NYC. Free shipping over $49.</p>`
  },
  {
    title:'How to Trim Your Dog\'s Nails at Home — Without the Stress',
    slug:'how-to-trim-dog-nails-at-home',
    petType:'dog', category:'Dog Care',
    tags:['how to trim dog nails','dog nail clipping NYC','dog grooming home Queens','dog nails apartment NYC'],
    img:'photo-1543466835-00a7907e9de1',
    meta:'How to trim dog nails at home without stress. Step-by-step guide, tools to use, and how to avoid cutting the quick. For NYC apartment dogs.',
    excerpt:'Long nails cause pain, posture problems, and floor damage. Here\'s how to trim your dog\'s nails at home — including what to do if you cut the quick.',
    content:`<h2>Why Nail Length Matters More for City Dogs</h2><p>Dogs who walk on sidewalks all day don't naturally wear their nails down the same way dogs with yard access do. NYC pavement does some of the work, but not enough — most city dogs still need trimming every 3-6 weeks. Overgrown nails force the foot to splay outward, stressing tendons and joints over time.</p><h2>What You Need</h2><ul><li>Sharp dog nail clippers (guillotine or scissor style) — dull ones crush rather than cut</li><li>Styptic powder (for accidental quicks)</li><li>High-value treats</li></ul><h2>The Quick — Know It Before You Cut</h2><p>The quick is the blood vessel and nerve inside each nail. Cutting it causes pain and bleeding. In light-colored nails you can see it as a pink section — cut just below it. In dark nails, you can't see it: make small slices (1-2mm at a time) and look at the cut surface. When you see a grayish/pink circle appear in the center, stop — you're close to the quick.</p><h2>Step-by-Step</h2><ol><li>Get your dog comfortable — pair nail handling with treats over several sessions before you try cutting.</li><li>Hold the paw firmly but gently. Extend one nail at a time.</li><li>For light nails: identify the quick, cut below it at a 45° angle.</li><li>For dark nails: take small slices until you see the gray/pink center.</li><li>If you hit the quick: apply styptic powder with light pressure for 60 seconds. Stay calm — your dog reads your energy.</li></ol><h2>Frequency</h2><p>Trim when you hear clicking on hard floors. For most NYC dogs: every 3-6 weeks.</p><p>Shop grooming supplies at <a href="https://www.petshiwu.com/dog">PetShiwu</a> — delivered to Queens and all of NYC. Free shipping over $49.</p>`
  },
  {
    title:'Dog Separation Anxiety in NYC Apartments — Causes, Signs, and Fixes',
    slug:'dog-separation-anxiety-nyc-apartment',
    petType:'dog', category:'Dog Care',
    tags:['dog separation anxiety NYC','apartment dog anxiety Queens','dog anxiety NYC','dog barking apartment NYC','dog anxiety treatment'],
    img:'photo-1529472119196-cb724127b673',
    meta:'Dog separation anxiety in NYC apartments — signs, causes, and treatments. For Queens, Brooklyn, and Manhattan dogs left alone while owners commute.',
    excerpt:'NYC commutes are long. Left alone in a small apartment for 8+ hours, many dogs develop separation anxiety. Here\'s what\'s actually happening — and how to fix it.',
    content:`<h2>Separation Anxiety Is Real — and Common in NYC</h2><p>Separation anxiety (SA) is a clinical condition, not stubbornness. When dogs with SA are left alone, they experience genuine panic — comparable to a human having a panic attack. In a small NYC apartment with thin walls and close neighbors, the results are: non-stop barking, destructive behavior, house accidents, and complaints from your building.</p><h2>True SA vs Normal Dog Behavior</h2><p>Not all problem behavior when alone is SA. Boredom and under-stimulation cause similar symptoms but have different solutions.</p><ul><li><strong>True SA:</strong> Panic starts immediately at departure cues (picking up keys, putting on shoes). Dog cannot settle even briefly. Behaviors like drooling, vomiting from stress, non-stop vocalization.</li><li><strong>Boredom/under-stimulation:</strong> Problem behavior happens after the dog has been alone a while. Dog can settle for periods. Responds to exercise and enrichment.</li></ul><h2>Fixes for True SA</h2><ul><li><strong>Systematic desensitization:</strong> Work with a trainer certified in SA (CSAT). The protocol involves training the dog to tolerate very short absences (seconds) and building up gradually over weeks.</li><li><strong>Medication:</strong> For moderate-severe SA, fluoxetine (Prozac) or clomipramine prescribed by a vet significantly improves outcomes when combined with behavior modification.</li><li><strong>Adaptil (DAP):</strong> Dog Appeasing Pheromone — available as a diffuser or collar. Clinical evidence supports mild calming effects.</li></ul><h2>Fixes for Boredom and Under-Stimulation</h2><ul><li>45-60 minute morning exercise before departure</li><li>Food puzzles and Kong stuffed with frozen food</li><li>Doggy daycare 2-3x per week</li><li>Dog walker at midday</li><li>Calming supplements (L-theanine, melatonin, CBD)</li></ul><p>Shop calming supplements and enrichment toys at <a href="https://www.petshiwu.com/dog">PetShiwu</a> — delivered to Queens and all of NYC.</p>`
  },
  {
    title:'How to Stop a Cat from Scratching Furniture — What Actually Works',
    slug:'how-to-stop-cat-scratching-furniture',
    petType:'cat', category:'Cat Care',
    tags:['stop cat scratching furniture NYC','cat scratch deterrent apartment','cat scratching couch Queens','cat scratching post NYC'],
    img:'photo-1514888286974-6c03e2ca1dba',
    meta:'How to stop cats from scratching furniture in NYC apartments. Deterrent sprays, scratch posts, tape, and training methods that actually work.',
    excerpt:'Scratching is normal cat behavior — redirecting it isn\'t. Here\'s what actually works to protect your NYC apartment furniture without declawing.',
    content:`<h2>Why Cats Scratch — It's Not Malicious</h2><p>Cats scratch to: mark territory (they have scent glands in their paws), maintain nail health (scratching removes the outer nail sheath), and stretch their bodies. You cannot stop a cat from scratching. You can redirect where they scratch.</p><h2>The Redirection Strategy</h2><p>Put a scratching post next to whatever they're scratching. Not across the room — right next to it. Cats scratch in prominent places because it's territorial marking. The post needs to be in the same spot to be appealing.</p><h2>What Makes a Good Scratch Post</h2><ul><li><strong>Tall enough:</strong> Cat must be able to fully extend — at least 32 inches tall</li><li><strong>Stable:</strong> Wobbles teach cats not to use it</li><li><strong>Sisal rope or cardboard:</strong> Not carpet (carpet on furniture teaches them carpet furniture is okay)</li><li><strong>Vertical AND horizontal:</strong> Some cats prefer horizontal scratchers (cardboard boxes work)</li></ul><h2>Deterrents for Furniture</h2><ul><li><strong>Sticky tape (Sticky Paws):</strong> Cats hate the feeling on their paws. Apply to the exact spot being scratched. Remove once they've adopted the post.</li><li><strong>Feliway spray:</strong> Synthetic facial pheromone — cats rub their face on things they consider safe. Spraying on furniture reduces marking behavior.</li><li><strong>Aluminum foil:</strong> Temporary deterrent. Cats dislike the feel and sound.</li><li><strong>Nail caps (Soft Paws):</strong> Vinyl caps glued over claws. Completely humane, lasts 4-6 weeks. Eliminates damage entirely.</li></ul><h2>What Doesn't Work</h2><ul><li>Punishment — increases anxiety and worsens marking behavior</li><li>Declawing — permanently disabling surgery; banned in many countries; causes chronic pain</li><li>Moving the post away from the furniture — defeats the purpose</li></ul><p>Shop scratch posts and deterrents at <a href="https://www.petshiwu.com/cat">PetShiwu</a> — delivered to Queens, Brooklyn, and all of NYC.</p>`
  },
  {
    title:'How to Give a Cat a Pill — 5 Methods That Work',
    slug:'how-to-give-cat-a-pill',
    petType:'cat', category:'Cat Care',
    tags:['how to give cat a pill','cat medication tips','pilling a cat NYC','cat pill pocket','cat medication Queens'],
    img:'photo-1574158622682-e40e69881006',
    meta:'How to give a cat a pill — 5 methods from pill pockets to pilling by hand. Step-by-step for NYC cat owners dealing with medications.',
    excerpt:'Giving a cat a pill is one of the most-feared pet tasks. Here are 5 methods — from simple food tricks to the proper hand technique — ranked by ease.',
    content:`<h2>Why Cats Are So Hard to Pill</h2><p>Dogs can usually be bribed with food. Cats are suspicious of everything, have a highly sensitive sense of smell, and will eat around a hidden pill with surgical precision. But millions of cats take daily medications successfully — it just takes the right technique.</p><h2>Method 1: Pill Pockets (Easiest)</h2><p>Pill Pockets are soft, moldable treats with a hole for a pill. Push the pill in, seal the pocket, offer as a treat. Works for cats who aren't pill-suspicious yet. Start giving them plain Pill Pockets before you need to hide a pill — so they learn the treat first, pill later.</p><h2>Method 2: Cream Cheese or Butter</h2><p>Coat the pill in a thin layer of cream cheese, butter, or meat-based baby food. The fat makes it slide down easily and the taste masks the pill. Works for cats who lick rather than chew.</p><h2>Method 3: Pill Gun / Piller</h2><p>A piller is a plastic syringe-like tool that holds the pill and lets you place it at the back of the throat without putting your fingers in. Less stressful for both parties than the hand method.</p><h2>Method 4: The Hand Method (Most Reliable)</h2><ol><li>Wrap cat in a towel (burrito wrap) if they struggle</li><li>Hold the cat's head from above — thumb on one side, fingers on the other</li><li>Tilt head back until nose points at ceiling</li><li>Lower jaw opens slightly — use your other hand's index finger to open it further</li><li>Drop pill as far back on tongue as possible</li><li>Close mouth, keep head tilted, gently blow on nose (triggers swallowing)</li><li>Offer a water syringe or treat to ensure swallowing</li></ol><h2>Method 5: Compounded Medication</h2><p>Ask your vet about compounding. Many cat medications can be reformulated as a flavored liquid (chicken or fish flavor) or a transdermal gel applied to the ear flap. Easiest method of all — if your vet offers it.</p><p>Shop treats and pill pockets at <a href="https://www.petshiwu.com/cat">PetShiwu</a> — delivered to Queens and all of NYC. Free shipping over $49.</p>`
  },
  {
    title:'Dog Dental Care at Home — Brushing, Chews, and Water Additives Ranked',
    slug:'dog-dental-care-at-home',
    petType:'dog', category:'Dog Care',
    tags:['dog dental care NYC','dog teeth brushing Queens','dog dental chews NYC','dog bad breath Queens','VOHC dental products dogs'],
    img:'photo-1537151608828-ea2b11777ee8',
    meta:'Dog dental care at home — brushing, dental chews, water additives, and sprays ranked by effectiveness. VOHC-approved options for NYC dog owners.',
    excerpt:'80% of dogs over 3 have dental disease. It causes pain, tooth loss, and links to heart and kidney disease. Here\'s how to prevent it at home.',
    content:`<h2>Why Dental Health Matters So Much</h2><p>Dental disease is the most common health condition in dogs — 80% of dogs over age 3 have some degree of periodontal disease. It's not just bad breath: bacteria from infected gums enter the bloodstream and damage the heart, kidneys, and liver over time. The good news: it's almost entirely preventable at home.</p><h2>The Gold Standard: Daily Brushing</h2><p>Nothing beats brushing. Use a dog-specific enzymatic toothpaste (human toothpaste contains xylitol — toxic to dogs) and a soft-bristle dog toothbrush or finger brush. Brush daily if possible, minimum 3x per week. The enzyme in dog toothpaste continues working after brushing, breaking down plaque even without rinsing.</p><h2>VOHC-Approved Products — The Only Seal That Matters</h2><p>The Veterinary Oral Health Council (VOHC) seal means the product has been clinically tested and proven to reduce plaque or tartar. Any dental product without this seal is marketing, not medicine.</p><ul><li><strong>Greenies Dental Treats:</strong> VOHC approved. Feed daily for best results. Size matters — use correct size for your dog's weight.</li><li><strong>CET Enzymatic Chews:</strong> VOHC approved. Rawhide-based with enzymatic action.</li><li><strong>Oravet Dental Hygiene Chews:</strong> VOHC approved. Delmopinol coating disrupts bacterial biofilm.</li><li><strong>Vetradent Water Additive:</strong> VOHC approved. Add to water bowl daily. Reduces bacteria in the mouth.</li></ul><h2>Dental Chews vs Brushing</h2><p>Chews help but don't replace brushing. Think of chews as flossing and brushing as actual toothbrushing — both have value, but one is more thorough.</p><h2>Professional Cleaning</h2><p>Even with great home care, most dogs need a professional dental cleaning under anesthesia every 1-3 years. This is the only way to clean below the gumline.</p><p>Shop Greenies and dental care at <a href="https://www.petshiwu.com/dog/dog-treats">PetShiwu</a> — delivered to Queens and all of NYC. Free shipping over $49.</p>`
  },
  {
    title:'How to Bathe a Cat — Yes, It\'s Possible Without Getting Destroyed',
    slug:'how-to-bathe-a-cat',
    petType:'cat', category:'Cat Care',
    tags:['how to bathe a cat','cat bath NYC','washing a cat Queens','cat grooming at home NYC','cat shampoo'],
    img:'photo-1533743983669-94fa5c4338ec',
    meta:'How to bathe a cat safely without getting scratched. Step-by-step for NYC cat owners who need to wash their cat at home.',
    excerpt:'Most cats never need a bath — but when they do (flea treatment, something they got into), here\'s how to do it without injury to either of you.',
    content:`<h2>Do Cats Actually Need Baths?</h2><p>Healthy adult cats are excellent self-groomers and almost never need baths. But there are situations where bathing is necessary: severe flea infestations requiring medicated shampoo, getting into something toxic or very sticky, heavily soiled long-haired cats, or senior/obese cats who can't self-groom. For these situations, here's how to survive it.</p><h2>Prepare Everything Before the Cat Knows What's Happening</h2><ul><li>Trim nails 24 hours before (not right before — they'll be on guard)</li><li>Gather: cat shampoo, 2-3 towels, non-slip mat, cup for rinsing</li><li>Use a sink or small tub — easier to control than a shower</li><li>Run warm water ahead of time (not hot, not cold — test on wrist)</li></ul><h2>Step-by-Step</h2><ol><li>Place non-slip mat in sink. Wet the cat from neck down with warm water using a cup — avoid the face and ears entirely.</li><li>Apply cat shampoo from neck to tail. Lather gently for 2 minutes. Work fast — the clock is ticking on their patience.</li><li>Rinse thoroughly. Shampoo residue causes skin irritation. Pour water over multiple times until water runs clear.</li><li>Wrap immediately in a warm towel. Pat dry — don't rub (causes tangles and upsets them more).</li><li>Keep them warm until fully dry. Indoor cats in air conditioning can get chilled easily.</li></ol><h2>What Not to Do</h2><ul><li>Don't use human shampoo — pH is wrong for cat skin</li><li>Don't use a hair dryer on high heat — burns and terrifies them. Low heat, held at distance, is okay for long-haired cats.</li><li>Don't get water in ears — causes infections</li></ul><p>Shop cat shampoo and grooming supplies at <a href="https://www.petshiwu.com/cat">PetShiwu</a> — delivered to your NYC apartment. Free shipping over $49.</p>`
  },
  {
    title:'Cat Hairball Remedies — What Works and What\'s Just Marketing',
    slug:'cat-hairball-remedies-what-works',
    petType:'cat', category:'Cat Care',
    tags:['cat hairball remedies NYC','cat hairball treatment Queens','cat vomiting hairballs','hairball control cat food','cat hairball gel'],
    img:'photo-1472491235688-bdc81a63246e',
    meta:'Cat hairball remedies ranked — what actually works vs marketing. Hairball gels, foods, brushing frequency, and when hairballs mean something serious.',
    excerpt:'Hairballs are normal but frequent ones signal a problem. Here\'s what actually reduces them — and when frequent vomiting means a vet visit.',
    content:`<h2>What Are Hairballs and Why Do Cats Get Them</h2><p>Cats groom constantly, swallowing loose hair in the process. Most hair passes through the digestive system without issue. Hairballs form when enough hair accumulates in the stomach to be expelled — up rather than through. Occasional hairballs (once a month or less) in a healthy cat are normal. Frequent hairballs (more than once a week) are not normal and need attention.</p><h2>What Actually Works</h2><h3>1. Brushing — The Most Effective Prevention</h3><p>Daily brushing removes loose hair before the cat swallows it. For long-haired cats, this alone dramatically reduces hairball frequency. A slicker brush or de-shedding tool (Furminator) reaches the undercoat where most loose hair accumulates.</p><h3>2. Hairball Control Food</h3><p>These formulas are higher in fiber (often from beet pulp or psyllium) which helps hair move through the digestive system instead of accumulating. Hill's Science Diet Hairball Control and Royal Canin Hairball Care have the most clinical evidence. Feed as the primary diet, not as a supplement.</p><h3>3. Petroleum-Based Gels (Laxatone, Petromalt)</h3><p>Lubricant gels — cats eat them off your finger (most like the malt flavor) and the petroleum helps hair slide through. Give 2-3x per week, not daily. Don't give within 2 hours of meals — interferes with fat-soluble vitamin absorption.</p><h3>4. Omega-3 Fatty Acids</h3><p>Fish oil added to food supports skin and coat health, reducing shedding overall. Less hair ingested means fewer hairballs. Dose: 500mg EPA/DHA per day for most cats.</p><h2>When Hairballs Are Not Hairballs</h2><p>If your cat is retching frequently but producing nothing, or if vomiting is increasing rapidly, see a vet. This can indicate intestinal obstruction, IBD, or hyperthyroidism — not hairballs.</p><p>Shop hairball control food and remedies at <a href="https://www.petshiwu.com/cat">PetShiwu</a> — delivered to Queens and all of NYC.</p>`
  },
  {
    title:'Puppy First Week Home Schedule — What to Do Day by Day',
    slug:'puppy-first-week-home-schedule',
    petType:'dog', category:'Dog Care',
    tags:['puppy first week home schedule','new puppy schedule NYC','puppy care first week Queens','puppy schedule apartment','NYC puppy guide'],
    img:'photo-1561037404-61cd46aa615b',
    meta:'Puppy first week home schedule — what to do hour by hour, day by day. For NYC apartment puppies in Queens, Brooklyn, and Manhattan.',
    excerpt:'The first week with a new puppy sets the foundation for everything. Here\'s the exact schedule and priorities for each day — tailored for NYC apartment life.',
    content:`<h2>Day 1: Just Let Them Breathe</h2><p>Don't invite people over. Don't try to train anything. Don't overwhelm with toys or attention. Day 1 is about the puppy learning that their new home is safe. Let them explore at their own pace. Show them where to sleep, where to eat, and take them outside every hour.</p><h2>The Daily Schedule (Weeks 1-2)</h2><ul><li><strong>6am:</strong> Immediately outside (before coffee, before anything)</li><li><strong>6:15am:</strong> Breakfast in crate or designated spot</li><li><strong>6:30am:</strong> Brief playtime, then outside again</li><li><strong>7:30am:</strong> Nap in crate (puppies need 16-18 hours of sleep)</li><li><strong>9:30am:</strong> Outside, then playtime</li><li><strong>10:30am:</strong> Nap</li><li><strong>12pm:</strong> Lunch + outside</li><li><strong>1pm:</strong> Nap</li><li><strong>3pm:</strong> Outside, playtime, brief training (5-minute sessions only)</li><li><strong>4pm:</strong> Nap</li><li><strong>5:30pm:</strong> Dinner + outside</li><li><strong>7pm:</strong> Calm evening activity — no rough play before bed</li><li><strong>9pm:</strong> Final outside trip</li><li><strong>9:30pm:</strong> Crate for the night</li><li><strong>2am:</strong> Nighttime outside trip (under 12 weeks — they can't hold it longer)</li></ul><h2>The Crate: Your Ally, Not a Punishment</h2><p>A crate keeps the puppy safe when unsupervised and accelerates housetraining. Feed meals in the crate. Put a worn t-shirt of yours inside. Cover with a blanket. Never use the crate as punishment.</p><h2>What to Buy for Week 1</h2><ul><li>Age-appropriate puppy food (small breed or large breed specific)</li><li>Crate with divider panel (size for adult, section off now)</li><li>Collar with ID tag — immediately</li><li>Enzyme cleaner for accidents</li><li>Kong toy for crate distraction</li></ul><p>Shop everything you need for your new puppy at <a href="https://www.petshiwu.com/dog">PetShiwu</a> — delivered to Queens and all of NYC. Free shipping over $49.</p>`
  },
  {
    title:'Why Is My Dog Scooting? Causes and When to Call the Vet',
    slug:'why-is-my-dog-scooting-causes',
    petType:'dog', category:'Dog Care',
    tags:['dog scooting causes','dog dragging bottom floor','dog anal glands NYC','dog scooting treatment Queens','anal gland expression dog'],
    img:'photo-1494947665470-20322015e3a8',
    meta:'Why dogs scoot — anal glands, parasites, allergies. When to express anal glands at home vs vet. NYC dog owner guide.',
    excerpt:'Scooting is embarrassing but common. Almost always it means one thing: full or impacted anal glands. Here\'s what to do and when to call the vet.',
    content:`<h2>What Scooting Means</h2><p>Scooting — dragging the rear end along the floor — almost always signals anal gland discomfort. The anal glands (two small scent glands inside the rectum) should express naturally when a dog defecates. When they don't empty fully, they cause itching, pressure, and discomfort — hence the scooting.</p><h2>Other Causes (Less Common)</h2><ul><li><strong>Tapeworms:</strong> Look for sesame seed-sized segments around the anus or in stool</li><li><strong>Allergies:</strong> Environmental or food allergies cause perianal itching alongside skin symptoms elsewhere</li><li><strong>Perianal irritation:</strong> After diarrhea or grooming — usually resolves quickly</li></ul><h2>Anal Gland Expression</h2><p>If the cause is anal glands (most common), they need to be expressed — either manually at a vet/groomer, or at home by experienced owners.</p><p><strong>External expression:</strong> Apply gentle pressure on both sides of the anus (4 and 8 o'clock positions) with a cloth. Normal secretion is liquid and brown. Impacted glands have a thick, pasty secretion. Infected glands have bloody or pus-filled secretion — these need a vet, not home expression.</p><h2>When to See a Vet Immediately</h2><ul><li>Visible swelling or lump on one side of the anus — possible abscess</li><li>Bloody discharge</li><li>Dog is in obvious pain — crying, won't sit</li><li>Repeated scooting within days of expression — impaction or infection</li></ul><h2>Prevention</h2><p>High-fiber diet helps keep stools firm, which naturally expresses the glands. Dogs prone to anal gland issues often benefit from pumpkin added to food (1-4 tablespoons per meal) or a high-fiber food formula.</p><p>Shop high-fiber dog food at <a href="https://www.petshiwu.com/dog/dog-food">PetShiwu</a> — delivered to Queens and all of NYC.</p>`
  },
  {
    title:'Best Dry Cat Food 2026 — Ranked by Protein, Ingredients, and Value',
    slug:'best-dry-cat-food-2026-ranked',
    petType:'cat', category:'Cat Care',
    tags:['best dry cat food 2026','top rated cat food NYC','dry cat food review Queens','best kibble for cats','high protein cat food NYC'],
    img:'photo-1513360371618-26c46f30c676',
    meta:'Best dry cat food 2026 ranked by protein content, ingredient quality, and value. Top picks for NYC cat owners delivered to Queens, Brooklyn, Manhattan.',
    excerpt:'Not all dry cat food is equal. Here are the top picks for 2026 — ranked by actual protein content, ingredient quality, and what\'s worth the price.',
    content:`<h2>How We Ranked These Foods</h2><p>Rankings based on: (1) dry matter protein content (not as-fed percentage), (2) quality of first 5 ingredients, (3) AAFCO substantiation method (feeding trials preferred), (4) absence of artificial preservatives, and (5) value per pound of protein.</p><h2>Best Dry Cat Food 2026</h2><h3>1. Purina Pro Plan — Best Overall</h3><p>Real salmon or chicken as #1 ingredient. AAFCO-substantiated by feeding trials (the stronger standard). Over 40% protein dry matter in the adult line. Made in USA. One of the most-researched cat foods available — backed by decades of veterinary nutrition data. Excellent value for the quality.</p><h3>2. Royal Canin — Best for Breed/Life Stage Needs</h3><p>Unmatched in life-stage and breed-specific formulation. Indoor Cat, Spayed/Neutered, Hairball, Urinary, and breed-specific lines are all backed by nutrition research. Slightly lower animal protein than others but compensates with precise targeting of specific health needs.</p><h3>3. Hill's Science Diet — Best for Sensitive Cats</h3><p>AAFCO feeding trial substantiated. Perfect Digestion and Sensitive Stomach lines are genuinely effective for cats with digestive issues. Trusted by vets worldwide. Like Purina Pro Plan, this is "prescription-grade care in an OTC package."</p><h3>4. Orijen — Best Premium Ingredient Quality</h3><p>85%+ animal ingredients, freeze-dried raw coating, regional sourcing. The highest ingredient quality available in cat food. Best for owners prioritizing ingredient transparency above all else. Premium price, but premium quality.</p><h3>5. Wellness CORE — Best Grain-Free Value</h3><p>80%+ protein from animal sources, no grains, no artificial additives. Good ingredient quality at a mid-tier price point. Best for cats doing well on grain-free who don't need the specialty formulation of Royal Canin or Hill's.</p><p>Shop all cat food at <a href="https://www.petshiwu.com/cat/cat-food">PetShiwu</a> — delivered to Queens, Brooklyn, and all of NYC. Free shipping over $49.</p>`
  },
  {
    title:'Best Dry Dog Food 2026 — Vet-Trusted Brands Ranked',
    slug:'best-dry-dog-food-2026-ranked',
    petType:'dog', category:'Dog Care',
    tags:['best dry dog food 2026','top rated dog food NYC','best kibble for dogs Queens','vet recommended dog food NYC','dry dog food review'],
    img:'photo-1548199973-03cce0bbc87b',
    meta:'Best dry dog food 2026 ranked by vets — Purina Pro Plan, Hill\'s, Royal Canin, Orijen and more. Top picks for NYC dogs delivered to Queens and Brooklyn.',
    excerpt:'Which dry dog food is actually worth buying? Here\'s the 2026 ranking — by protein quality, vet endorsement, and what the nutrition research actually shows.',
    content:`<h2>What Makes a Dog Food Worth Recommending</h2><p>The pet food industry is full of marketing. "Grain-free," "raw," "human-grade," "holistic" — none of these terms are regulated and none guarantee quality. What actually matters: AAFCO feeding trial substantiation, real named animal proteins in the first few ingredients, a brand with a full-time veterinary nutritionist on staff, and recall history.</p><h2>Best Dry Dog Food 2026</h2><h3>1. Purina Pro Plan — Best Overall, Best Value</h3><p>The #1 recommendation of board-certified veterinary nutritionists in survey after survey. Real meat first. Multiple AAFCO feeding trial substantiated formulas. Purina has over 500 scientists and veterinarians on staff. Extensive research backing for specific health conditions. Outstanding value for a food of this quality.</p><h3>2. Hill's Science Diet — Best for Specific Health Needs</h3><p>The gold standard for dogs with health conditions. If your dog has joint issues, kidney disease, weight problems, or sensitive digestion — Hill's has a clinically-proven formula for it. Prescription Diet lines require vet authorization; Science Diet (OTC) covers most common needs.</p><h3>3. Royal Canin — Best for Breed-Specific Nutrition</h3><p>No other brand goes as deep on breed-specific formulation. Kibble shapes sized for specific breeds' jaw anatomy. Formulas developed for French Bulldogs, Labradors, Yorkies, and 30+ other breeds. If you have a purebred, Royal Canin's specific formula is hard to beat.</p><h3>4. Orijen — Best Premium Ingredients</h3><p>For owners who prioritize ingredient quality above all: 85%+ animal ingredients, biologically appropriate ratios, regional sourcing, and no artificial additives. The Rolls Royce of dry dog food. Premium price matches the quality.</p><h3>5. Merrick — Best Mid-Tier Choice</h3><p>Real deboned meat first, made in USA, no artificial anything. A strong choice for dogs doing well without needing specialty health formulas. Good value for a quality mid-tier product.</p><p>Shop all dog food at <a href="https://www.petshiwu.com/dog/dog-food">PetShiwu</a> — delivered to Queens, Brooklyn, and all NYC. Free shipping over $49.</p>`
  },
];

async function main() {
  const token = await login();
  console.log(`Publishing ${posts.length} how-to and ranking posts...\n`);
  let ok=0,fail=0;
  for (const p of posts) {
    const success = await pub(token, {
      title:p.title, slug:p.slug, petType:p.petType, category:p.category,
      tags:p.tags, excerpt:p.excerpt, content:p.content,
      featuredImage:`https://images.unsplash.com/${p.img}?w=1200&q=80`,
      metaTitle:p.title, metaDescription:p.meta,
    });
    success?ok++:fail++;
    await new Promise(r=>setTimeout(r,350));
  }
  console.log(`\nPublished: ${ok} | Failed: ${fail}`);
}
main();
